In [78]:
import numpy as np
np.__version__

'1.23.0'

In [79]:
summ = 0
for num in range(1,9999999):
    summ+=num**2*3

In [80]:
summ

999999550000064999997

In [81]:
np.sum(np.arange(1,9999999, dtype=np.int64))

49999985000001

# Array Creation

In [82]:
np.zeros([4,3,3], dtype=np.int64)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [83]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [85]:
np.empty([3,3,3])

array([[[6.23042070e-307, 3.56043053e-307, 1.37961641e-306],
        [1.60216182e-306, 7.56602523e-307, 1.33511562e-306],
        [2.22518251e-306, 1.33511969e-306, 2.22520288e-307]],

       [[1.24611538e-306, 1.33511290e-306, 1.11261027e-306],
        [1.11261502e-306, 1.42410839e-306, 7.56597770e-307],
        [6.23059726e-307, 1.42419530e-306, 7.56599128e-307]],

       [[1.11260144e-306, 6.89812281e-307, 1.42418172e-306],
        [8.06609645e-308, 6.89810244e-307, 1.22387550e-307],
        [2.22522596e-306, 8.90111707e-307, 2.29175545e-312]]])

In [86]:
np.full([3,3],8.5)

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [87]:
np.arange(5,5555,5)

array([   5,   10,   15, ..., 5540, 5545, 5550])

In [88]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [89]:
np.random.randint(2,4)

3

In [90]:
np.random.randn(50)

array([ 0.77202725, -0.92381046,  1.10432427,  1.20899658, -1.55449241,
       -1.4690093 ,  2.27273308,  0.55111229,  0.73047164,  0.10535   ,
       -0.20480237,  1.08000565, -1.21908928, -0.94598836, -0.12746146,
       -0.66764535,  0.25159487, -0.10587797,  0.40147848, -0.93266047,
        0.44286457,  0.01025995, -1.32536931,  1.06784144, -0.71644717,
        0.84780985, -0.15359762, -0.59175563, -0.12013798, -0.94979475,
       -0.36701341,  0.24971563,  1.27795172, -1.408827  ,  0.98075109,
        0.51810493,  0.53070994,  0.29078416, -0.9381526 ,  2.28129595,
       -0.70392861,  1.1716271 ,  0.89994207,  0.39020238, -1.23509733,
       -1.37403023, -1.1548522 ,  0.38077242, -0.88158496, -0.99504486])

# Type of Array

In [91]:
integr = np.array([2,3,54,563,6], dtype=np.int64)
integr

array([  2,   3,  54, 563,   6], dtype=int64)

In [92]:
float = np.array([2,3,54,563,6], dtype=np.float64)
float

array([  2.,   3.,  54., 563.,   6.])

In [93]:
bool = np.array([True, False, True, False], dtype=np.bool8)
bool

array([ True, False,  True, False])

In [94]:
empty = np.empty([3,3], dtype=np.complex64)
empty

array([[0.+2.515625j, 0.+2.515625j, 0.+2.515625j],
       [0.+2.515625j, 0.+2.515625j, 0.+2.515625j],
       [0.+2.515625j, 0.+2.515625j, 0.+2.515625j]], dtype=complex64)

In [95]:
string = np.array(["apple","banana", 'grapes'], dtype=np.string_)
string

array([b'apple', b'banana', b'grapes'], dtype='|S6')

# NDarray Object Inspection

In [96]:
string.ndim
empty.ndim

2

In [97]:
empty.shape
integr.shape

(5,)

In [98]:
empty.itemsize
string.itemsize
string.item(0)

b'apple'

In [99]:
bool.any()
bool.all()

False

In [100]:
empty.dtype
integr.itemsize
string.dtype

dtype('S6')

In [101]:
empty.size

9

# Slicing

In [102]:
arr = np.array(
    [
        [44,22,56,79],
        [67,76,89,79],
        [52,45,78,79],
        [13,53,64,88]
    ]
)

In [103]:
arr[1:3:2,0:4:2]

array([[67, 89]])

In [104]:
arr[1:,2:]

array([[89, 79],
       [78, 79],
       [64, 88]])

In [105]:
arr[1:3,1:3]

array([[76, 89],
       [45, 78]])

# Filtering

In [106]:
arr>50

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True]])

In [107]:
arr[arr>50]

array([56, 79, 67, 76, 89, 79, 52, 78, 79, 53, 64, 88])

In [108]:
arr[(arr>50) & (arr<60)]

array([56, 52, 53])

In [109]:
arr[(arr%2==0)]

array([44, 22, 56, 76, 52, 78, 64, 88])

In [110]:
arr[~arr%2==0]

array([79, 67, 89, 79, 45, 79, 13, 53])

# Operator

In [111]:
arr2 = arr[1:,1:]
arr2

array([[76, 89, 79],
       [45, 78, 79],
       [53, 64, 88]])

In [112]:
arr2*2

array([[152, 178, 158],
       [ 90, 156, 158],
       [106, 128, 176]])

In [113]:
arr/2

array([[22. , 11. , 28. , 39.5],
       [33.5, 38. , 44.5, 39.5],
       [26. , 22.5, 39. , 39.5],
       [ 6.5, 26.5, 32. , 44. ]])

In [114]:
arr//2

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [115]:
arr2**2

array([[5776, 7921, 6241],
       [2025, 6084, 6241],
       [2809, 4096, 7744]])

In [116]:
arr3 = arr2%2
arr3

array([[0, 1, 1],
       [1, 0, 1],
       [1, 0, 0]], dtype=int32)

# Matrix Operation

In [117]:
arr2 + arr3

array([[76, 90, 80],
       [46, 78, 80],
       [54, 64, 88]])

In [118]:
arr2 * arr3

array([[ 0, 89, 79],
       [45,  0, 79],
       [53,  0,  0]])

In [119]:
arr2 - arr3

array([[76, 88, 78],
       [44, 78, 78],
       [52, 64, 88]])

In [120]:
arr4 = arr2 **arr3
arr4

array([[ 1, 89, 79],
       [45,  1, 79],
       [53,  1,  1]], dtype=int32)

In [121]:
arr2@arr3

array([[168,  76, 165],
       [157,  45, 123],
       [152,  53, 117]])

In [122]:
np.matmul(arr2,arr4)

array([[ 8268,  6932, 13114],
       [ 7742,  4162,  9796],
       [ 7597,  4869,  9331]])

In [123]:
np.multiply(arr3,arr3)

array([[0, 1, 1],
       [1, 0, 1],
       [1, 0, 0]], dtype=int32)

In [124]:
np.divide(arr2, arr4)

array([[76.,  1.,  1.],
       [ 1., 78.,  1.],
       [ 1., 64., 88.]])

# Load and Save NumPy Array

In [125]:
np.save('arr4', arr4, allow_pickle=True)

In [126]:
np.load('arr4.npy')

array([[ 1, 89, 79],
       [45,  1, 79],
       [53,  1,  1]])

# Stats

In [127]:
arr

array([[44, 22, 56, 79],
       [67, 76, 89, 79],
       [52, 45, 78, 79],
       [13, 53, 64, 88]])

In [128]:
arr.mean()

61.5

In [129]:
arr.mean(axis=0)

array([44.  , 49.  , 71.75, 81.25])

In [130]:
arr.mean(axis=1)

array([50.25, 77.75, 63.5 , 54.5 ])

In [131]:
np.std(arr, axis=0)

array([19.71040334, 19.30025907, 12.69596393,  3.89711432])

In [132]:
np.std(arr, axis=1)

array([20.59581268,  7.85413904, 15.20690633, 27.09704781])

In [133]:
np.var(arr, axis=1)

array([424.1875,  61.6875, 231.25  , 734.25  ])

In [134]:
x = np.arange(1,10)
y = np.arange(11,20)
np.cov(x,y)

array([[7.5, 7.5],
       [7.5, 7.5]])

In [135]:
np.cov(arr)

array([[565.58333333,  72.41666667, 374.5       , 439.83333333],
       [ 72.41666667,  82.25      , 112.83333333, 199.16666667],
       [374.5       , 112.83333333, 308.33333333, 387.33333333],
       [439.83333333, 199.16666667, 387.33333333, 979.        ]])

In [136]:
arr.sum(axis=1)

array([201, 311, 254, 218])

In [137]:
np.sum(arr, axis=1)

array([201, 311, 254, 218])

In [138]:
arr.min(axis=0)

array([13, 22, 56, 79])

In [139]:
arr.max(axis=1)

array([79, 89, 79, 88])

In [140]:
x = np.random.rand(10)
x

array([0.83509881, 0.66772   , 0.77901068, 0.12666875, 0.59238442,
       0.57101393, 0.10664327, 0.67047973, 0.17865642, 0.11462084])

In [141]:
np.argmax(x)

0

In [142]:
np.argmin(x)

6

In [143]:
np.argsort(x)

array([6, 9, 3, 8, 5, 4, 1, 7, 2, 0], dtype=int64)

In [144]:
from numpy import linalg as lg


In [145]:
arr4

array([[ 1, 89, 79],
       [45,  1, 79],
       [53,  1,  1]], dtype=int32)

In [146]:
lg.det(arr4)

367928.00000000006

In [147]:
lg.inv(arr4)

array([[-2.11998000e-04, -2.71792307e-05,  1.88950012e-02],
       [ 1.12576374e-02, -1.13772260e-02,  9.44750060e-03],
       [-2.17433846e-05,  1.28177252e-02, -1.08825640e-02]])

In [148]:
arr4.transpose()

array([[ 1, 45, 53],
       [89,  1,  1],
       [79, 79,  1]], dtype=int32)

In [149]:
np.dot(arr3, arr4)

array([[98,  2, 80],
       [54, 90, 80],
       [ 1, 89, 79]], dtype=int32)

In [150]:
lg.eig(arr4)

(array([109.36342795 +0.j        , -53.18171397+23.15112064j,
        -53.18171397-23.15112064j]),
 array([[-0.73519404+0.j        , -0.67918848+0.j        ,
         -0.67918848-0.j        ],
        [-0.57129064+0.j        , -0.08402326-0.39573291j,
         -0.08402326+0.39573291j],
        [-0.36485165+0.j        ,  0.56047679+0.24678803j,
          0.56047679-0.24678803j]]))

In [151]:
lg.svd(arr4)

(array([[-0.83105542,  0.50099984,  0.24154927],
        [-0.54741345, -0.65993352, -0.51461273],
        [-0.09841444, -0.55989902,  0.82269538]]),
 array([135.60369612,  74.28767176,  36.52368303]),
 array([[-0.22625214, -0.55020447, -0.80379413],
        [-0.79246873,  0.58380014, -0.17655231],
        [ 0.56639499,  0.59703638, -0.56810587]]))

In [152]:
lg.norm(arr4)

158.8741640418605

In [153]:
np.cos(arr4)

array([[ 0.54030231,  0.51017704, -0.89597095],
       [ 0.52532199,  0.54030231, -0.89597095],
       [-0.91828279,  0.54030231,  0.54030231]])

In [154]:
np.tan(arr3)

array([[0.        , 1.55740772, 1.55740772],
       [1.55740772, 0.        , 1.55740772],
       [1.55740772, 0.        , 0.        ]])