In [1]:
import numpy as np
np.__version__

'1.23.0'

In [2]:
summ = 0
for num in range(1,9999999):
    summ+=num**2*3

In [3]:
summ

999999550000064999997

In [4]:
np.sum(np.arange(1,9999999, dtype=np.int64))

49999985000001

# Array Creation

In [5]:
np.zeros([4,3,3], dtype=np.int64)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int64)

In [6]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.eye(6,6, k=0)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [8]:
np.empty([3,3,3])

array([[[6.23042070e-307, 3.56043053e-307, 1.37961641e-306],
        [1.60216182e-306, 7.56602523e-307, 1.33511562e-306],
        [2.22518251e-306, 1.33511969e-306, 4.89544090e-307]],

       [[8.90102881e-307, 1.95821439e-306, 8.01097889e-307],
        [1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
        [1.33510679e-306, 2.22522597e-306, 6.23053614e-307]],

       [[2.22522597e-306, 1.06810268e-306, 6.23052935e-307],
        [9.34608432e-307, 2.22522597e-306, 1.33511969e-306],
        [8.90071135e-308, 8.45610231e-307, 3.20552953e-317]]])

In [9]:
np.full([3,3],8.5)

array([[8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5],
       [8.5, 8.5, 8.5]])

In [10]:
np.arange(5,5555,5)

array([   5,   10,   15, ..., 5540, 5545, 5550])

In [11]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [12]:
np.random.randint(2,4)

2

In [13]:
np.random.randn(50)

array([ 1.68226613, -0.93463399, -3.65531621, -0.41237422,  0.43866542,
        0.29768472,  0.81401032, -0.12452961,  0.08327974,  0.98359468,
        0.42193227,  0.29183639,  0.57007324, -0.30021864, -0.37623852,
        2.22741268, -0.46771896, -0.06069875, -0.09863275,  0.30819951,
        0.71866024, -0.71124327, -2.26848426, -0.52950309, -1.30018949,
       -0.97115649, -0.99951963, -0.21425807,  0.45412823,  0.19339056,
       -0.72385239,  1.01385012,  1.48336821,  1.08850836,  0.12550048,
       -1.2141687 ,  2.34870332,  1.01816267, -0.2434095 , -0.22384802,
        0.12600625,  1.43444071, -0.12901198,  1.66431435,  0.52886685,
       -0.04679111,  0.04232737, -0.29621614, -1.28699693,  1.67418859])

# Type of Array

In [14]:
integr = np.array([2,3,54,563,6], dtype=np.int64)
integr

array([  2,   3,  54, 563,   6], dtype=int64)

In [15]:
float = np.array([2,3,54,563,6], dtype=np.float64)
float

array([  2.,   3.,  54., 563.,   6.])

In [16]:
bool = np.array([True, False, True, False], dtype=np.bool8)
bool

array([ True, False,  True, False])

In [17]:
empty = np.empty([3,3], dtype=np.complex64)
empty

array([[0.+2.515625j, 0.+2.515625j, 0.+2.515625j],
       [0.+2.515625j, 0.+2.515625j, 0.+2.515625j],
       [0.+2.515625j, 0.+2.515625j, 0.+2.515625j]], dtype=complex64)

In [18]:
string = np.array(["apple","banana", 'grapes'], dtype=np.string_)
string

array([b'apple', b'banana', b'grapes'], dtype='|S6')

# NDarray Object Inspection

In [19]:
string.ndim
empty.ndim

2

In [20]:
empty.shape
integr.shape

(5,)

In [21]:
empty.itemsize
string.itemsize
string.item(0)

b'apple'

In [22]:
bool.any()
bool.all()

False

In [23]:
empty.dtype
integr.itemsize
string.dtype

dtype('S6')

In [24]:
empty.size

9

# Slicing

In [25]:
arr = np.array(
    [
        [44,22,56,79],
        [67,76,89,79],
        [52,45,78,79],
        [13,53,64,88]
    ]
)

In [26]:
arr[1:3:2,0:4:2]

array([[67, 89]])

In [27]:
arr[1:,2:]

array([[89, 79],
       [78, 79],
       [64, 88]])

In [28]:
arr[1:3,1:3]

array([[76, 89],
       [45, 78]])

# Filtering

In [29]:
arr>50

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False,  True,  True,  True]])

In [30]:
arr[arr>50]

array([56, 79, 67, 76, 89, 79, 52, 78, 79, 53, 64, 88])

In [31]:
arr[(arr>50) & (arr<60)]

array([56, 52, 53])

In [32]:
arr[(arr%2==0)]

array([44, 22, 56, 76, 52, 78, 64, 88])

In [33]:
arr[~arr%2==0]

array([79, 67, 89, 79, 45, 79, 13, 53])

# Operator

In [34]:
arr2 = arr[1:,1:]
arr2

array([[76, 89, 79],
       [45, 78, 79],
       [53, 64, 88]])

In [35]:
arr2*2

array([[152, 178, 158],
       [ 90, 156, 158],
       [106, 128, 176]])

In [36]:
arr/2

array([[22. , 11. , 28. , 39.5],
       [33.5, 38. , 44.5, 39.5],
       [26. , 22.5, 39. , 39.5],
       [ 6.5, 26.5, 32. , 44. ]])

In [37]:
arr//2

array([[22, 11, 28, 39],
       [33, 38, 44, 39],
       [26, 22, 39, 39],
       [ 6, 26, 32, 44]], dtype=int32)

In [38]:
arr2**2

array([[5776, 7921, 6241],
       [2025, 6084, 6241],
       [2809, 4096, 7744]])

In [39]:
arr3 = arr2%2
arr3

array([[0, 1, 1],
       [1, 0, 1],
       [1, 0, 0]], dtype=int32)

# Matrix Operation

In [40]:
arr2 + arr3

array([[76, 90, 80],
       [46, 78, 80],
       [54, 64, 88]])

In [41]:
arr2 * arr3

array([[ 0, 89, 79],
       [45,  0, 79],
       [53,  0,  0]])

In [42]:
arr2 - arr3

array([[76, 88, 78],
       [44, 78, 78],
       [52, 64, 88]])

In [43]:
arr4 = arr2 **arr3
arr4

array([[ 1, 89, 79],
       [45,  1, 79],
       [53,  1,  1]], dtype=int32)

In [44]:
arr2@arr3

array([[168,  76, 165],
       [157,  45, 123],
       [152,  53, 117]])

In [45]:
np.matmul(arr2,arr4)

array([[ 8268,  6932, 13114],
       [ 7742,  4162,  9796],
       [ 7597,  4869,  9331]])

In [46]:
np.multiply(arr3,arr3)

array([[0, 1, 1],
       [1, 0, 1],
       [1, 0, 0]], dtype=int32)

In [47]:
np.divide(arr2, arr4)

array([[76.,  1.,  1.],
       [ 1., 78.,  1.],
       [ 1., 64., 88.]])

# Load and Save NumPy Array

In [48]:
np.save('arr4', arr4, allow_pickle=True)

In [49]:
np.load('arr4.npy')

array([[ 1, 89, 79],
       [45,  1, 79],
       [53,  1,  1]])

# Stats

In [50]:
arr

array([[44, 22, 56, 79],
       [67, 76, 89, 79],
       [52, 45, 78, 79],
       [13, 53, 64, 88]])

In [51]:
arr.mean()

61.5

In [52]:
arr.mean(axis=0)

array([44.  , 49.  , 71.75, 81.25])

In [53]:
arr.mean(axis=1)

array([50.25, 77.75, 63.5 , 54.5 ])

In [54]:
np.std(arr, axis=0)

array([19.71040334, 19.30025907, 12.69596393,  3.89711432])

In [55]:
np.std(arr, axis=1)

array([20.59581268,  7.85413904, 15.20690633, 27.09704781])

In [56]:
np.var(arr, axis=1)

array([424.1875,  61.6875, 231.25  , 734.25  ])

In [57]:
x = np.arange(1,10)
y = np.arange(11,20)
np.cov(x,y)

array([[7.5, 7.5],
       [7.5, 7.5]])

In [58]:
np.cov(arr)

array([[565.58333333,  72.41666667, 374.5       , 439.83333333],
       [ 72.41666667,  82.25      , 112.83333333, 199.16666667],
       [374.5       , 112.83333333, 308.33333333, 387.33333333],
       [439.83333333, 199.16666667, 387.33333333, 979.        ]])